#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <mmsystem.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#pragma comment(lib, "winmm.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "user32.lib")

#define PLAY_AUDIO            // comment out to remove audio
#define FPS 45                // hacky way of speeding up animation
#define CHANCE (FPS * 60 * 5) // 5 minute (average)
#define DELAY_MS 700          // time to force wait between animation(s)
#define FRAME_MS (1000 / FPS)

#include "assets_embedded.h" // generated by tools/embed_assets.py

HWND hwnd;

int screen_w, screen_h;

int atlas_w, atlas_h;
int frame_w, frame_h;

// make sure to update this with your proper atlas data! (check assets/meta.json)
int cols = 6;
int rows = 5;
int frame_count = 27;

unsigned char* atlas_rgba = NULL;
unsigned char* atlas_bgra = NULL;

int frame = 0;
int playing = 0;

DWORD trigger_time = 0;
DWORD last_tick = 0;

void ensure_dir(const char* path)
{
    CreateDirectoryA(path, NULL);
}

void extract_file(const char* path, const unsigned char* data, size_t size)
{
    FILE* f = fopen(path, "rb");
    if (f)
    {
        fclose(f);
        return;
    }

    f = fopen(path, "wb");
    fwrite(data, 1, size, f);
    fclose(f);
}

void init_assets()
{
    char base[MAX_PATH];
    GetTempPathA(MAX_PATH, base);

    char dir[MAX_PATH];
    sprintf(dir, "%s\\overlay", base);
    ensure_dir(dir);

    char atlas_path[MAX_PATH];
    char audio_path[MAX_PATH];

    sprintf(atlas_path, "%s\\atlas.png", dir);
    sprintf(audio_path, "%s\\riff.mp3", dir);

    extract_file(atlas_path, ATLAS_PNG, ATLAS_PNG_SIZE);
    extract_file(audio_path, RIFF_MP3, RIFF_MP3_SIZE);
}

void audio_init()
{
    char base[MAX_PATH];
    GetTempPathA(MAX_PATH, base);

    char path[MAX_PATH];
    sprintf(path, "%s\\overlay\\riff.mp3", base);

    char cmd[512];
    sprintf(cmd, "open \"%s\" type mpegvideo alias riff", path);

    mciSendStringA("close riff", NULL, 0, NULL);
    mciSendStringA(cmd, NULL, 0, NULL);
}

void play_audio()
{
    mciSendStringA("seek riff to start", NULL, 0, NULL);
    mciSendStringA("play riff", NULL, 0, NULL);
}

void load_atlas()
{
    char base[MAX_PATH];
    GetTempPathA(MAX_PATH, base);

    char path[MAX_PATH];
    sprintf(path, "%s\\overlay\\atlas.png", base);

    int c;
    atlas_rgba = stbi_load(path, &atlas_w, &atlas_h, &c, 4);

    if (!atlas_rgba)
    {
        MessageBoxA(NULL, "Failed to load atlas", "Error", MB_OK);
        exit(1);
    }

    frame_w = atlas_w / cols;
    frame_h = atlas_h / rows;

    atlas_bgra = (unsigned char*)malloc(atlas_w * atlas_h * 4);

    for (int i = 0; i < atlas_w * atlas_h; i++)
    {
        unsigned char r = atlas_rgba[i * 4 + 0];
        unsigned char g = atlas_rgba[i * 4 + 1];
        unsigned char b = atlas_rgba[i * 4 + 2];
        unsigned char a = atlas_rgba[i * 4 + 3];

        atlas_bgra[i * 4 + 0] = (b * a) / 255;
        atlas_bgra[i * 4 + 1] = (g * a) / 255;
        atlas_bgra[i * 4 + 2] = (r * a) / 255;
        atlas_bgra[i * 4 + 3] = a;
    }
}

void render()
{
    HDC screen = GetDC(NULL);
    HDC memDC = CreateCompatibleDC(screen);

    BITMAPINFO bmi = {0};
    bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    bmi.bmiHeader.biWidth = screen_w;
    bmi.bmiHeader.biHeight = -screen_h;
    bmi.bmiHeader.biPlanes = 1;
    bmi.bmiHeader.biBitCount = 32;
    bmi.bmiHeader.biCompression = BI_RGB;

    unsigned char* buffer = NULL;

    HBITMAP dib = CreateDIBSection(screen, &bmi, DIB_RGB_COLORS, (void**)&buffer, NULL, 0);
    SelectObject(memDC, dib);

    ZeroMemory(buffer, screen_w * screen_h * 4);

    if (playing)
    {
        int fx = frame % cols;
        int fy = frame / cols;

        int sx = fx * frame_w;
        int sy = fy * frame_h;

        float scale_x = (float)screen_w / frame_w;
        float scale_y = (float)screen_h / frame_h;
        float scale = (scale_x < scale_y) ? scale_x : scale_y;

        int dw = (int)(frame_w * scale);
        int dh = (int)(frame_h * scale);

        int dx = (screen_w - dw) / 2;
        int dy = (screen_h - dh) / 2;

        for (int y = 0; y < dh; y++)
        {
            for (int x = 0; x < dw; x++)
            {
                int src_x = sx + (x * frame_w) / dw;
                int src_y = sy + (y * frame_h) / dh;

                int si = (src_y * atlas_w + src_x) * 4;
                int di = ((dy + y) * screen_w + (dx + x)) * 4;

                buffer[di + 0] = atlas_bgra[si + 0];
                buffer[di + 1] = atlas_bgra[si + 1];
                buffer[di + 2] = atlas_bgra[si + 2];
                buffer[di + 3] = atlas_bgra[si + 3];
            }
        }
    }

    POINT pt = {0, 0};
    SIZE sz = {screen_w, screen_h};

    BLENDFUNCTION bf = { AC_SRC_OVER, 0, 255, AC_SRC_ALPHA };

    UpdateLayeredWindow(hwnd, screen, &pt, &sz, memDC, &pt, 0, &bf, ULW_ALPHA);

    DeleteObject(dib);
    DeleteDC(memDC);
    ReleaseDC(NULL, screen);
}

LRESULT CALLBACK WndProc(HWND h, UINT m, WPARAM w, LPARAM l)
{
    if (m == WM_DESTROY)
        PostQuitMessage(0);
    return DefWindowProc(h, m, w, l);
}

int WINAPI WinMain(HINSTANCE h, HINSTANCE p, LPSTR l, int n)
{
    srand((unsigned)time(NULL));

    screen_w = GetSystemMetrics(SM_CXSCREEN);
    screen_h = GetSystemMetrics(SM_CYSCREEN);

    init_assets();
    audio_init();
    load_atlas();

    WNDCLASS wc = {0};
    wc.lpfnWndProc = WndProc;
    wc.hInstance = h;
    wc.lpszClassName = "overlay";

    RegisterClass(&wc);

    hwnd = CreateWindowEx(
        WS_EX_LAYERED | WS_EX_TRANSPARENT | WS_EX_TOPMOST,
        "overlay",
        "overlay",
        WS_POPUP,
        0, 0, screen_w, screen_h,
        NULL, NULL, h, NULL
    );

    ShowWindow(hwnd, SW_SHOW);

    last_tick = GetTickCount();

    MSG msg;

    while (1)
    {
        while (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))
        {
            if (msg.message == WM_QUIT)
                return 0;
            DispatchMessage(&msg);
        }

        DWORD now = GetTickCount();

        if (!playing && (rand() % CHANCE) == 0)
        {
#ifdef PLAY_AUDIO
            play_audio();
#endif
            trigger_time = now + DELAY_MS;
        }

        if (trigger_time && now >= trigger_time)
        {
            playing = 1;
            frame = 0;
            trigger_time = 0;
        }

        if (playing && now - last_tick > (1000 / FPS))
        {
            frame++;
            if (frame >= frame_count)
                playing = 0;

            last_tick = now;
        }

        render();
        Sleep(FRAME_MS);
    }
}